services:
  frontend_app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    container_name: frontend_app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - DISABLE_ESLINT_PLUGIN=true
      - NPM_CONFIG_CACHE=/home/appuser/.npm
      - NPM_CONFIG_PREFIX=/home/appuser/.npm-global
      # Dynamic backend URL based on host
      - REACT_APP_BACKEND_URL=http://${HOST:-localhost}:8000
    volumes:
      - ./frontend:/usr/src/app:cached
      - frontend_node_modules:/usr/src/app/node_modules
      - frontend_npm_cache:/home/appuser/.npm
      - frontend_npm_global:/home/appuser/.npm-global
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    stdin_open: true
    tty: true
    networks:
      - app-network

  backend_app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_HOST=database
      - DB_PORT=5432
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AI_ANALYZER_OPENAI_API_KEY=${AI_ANALYZER_OPENAI_API_KEY}
      - URL=${URL}
      - API_KEY=${API_KEY}
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - READ_USER=${READ_USER}
      - READ_USER_PASSWORD=${READ_USER_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      ## Add CORS allowed origins
      - ALLOWED_ORIGINS=http://localhost:3000,http://108.143.207.17:3000,http://127.0.0.1:3000
      # Add host environment variable
      - HOST=${HOST:-localhost}
    volumes:
      - ./backend:/usr/src/app
    command:
      [
        "uvicorn",
        "ai_analyzer.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload",
      ]
    healthcheck:
      test: >
        /bin/sh -c '
        TOKEN=$$(curl -s -X POST http://localhost:8000/api/login -H "Content-Type: application/json" -d "{\"username\":\"$$ADMIN_USER\",\"password\":\"$$ADMIN_PASSWORD\"}" | jq -r .access_token) &&
        curl -f -H "Authorization: Bearer $$TOKEN" http://localhost:8000/health || exit 1'
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 180s
    stdin_open: true
    tty: true
    networks:
      - app-network

volumes:
  frontend_node_modules:
    name: ai_analyzer_frontend_node_modules
    driver: local
  frontend_npm_cache:
    name: ai_analyzer_frontend_npm_cache
    driver: local
  frontend_npm_global:
    name: ai_analyzer_frontend_npm_global
    driver: local
  frontend_cache:
    name: ai_analyzer_frontend_cache
    driver: local

networks:
  app-network:
    external: true
    name: app_app-network