services:
  database:
    image: postgres:13
    container_name: postgres_db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST_AUTH_METHOD=md5
      - "listen_addresses=*"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    stdin_open: true
    tty: true
    networks:
      - app-network

  db_init:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - TARGETPLATFORM=linux/arm64
    container_name: db_init
    depends_on:
      database:
        condition: service_healthy
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_HOST=database
      - DB_PORT=5432
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - READ_USER=${READ_USER}
      - READ_USER_PASSWORD=${READ_USER_PASSWORD}
    volumes:
      - ./backend:/usr/src/app:delegated
      - ./backend/init_db.py:/usr/src/app/init_db.py:ro
    command: ["python", "/usr/src/app/init_db.py"]
    networks:
      - app-network

  vector_index_init:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - TARGETPLATFORM=linux/arm64
    container_name: vector_index_init
    depends_on:
      qdrant:
        condition: service_healthy
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - RECIPE_COLLECTION_NAME=food_recipes_two_step
      - EMBEDDING_MODEL=paraphrase-multilingual-MiniLM-L12-v2
      - RECIPE_DATA_DIR=/usr/src/app/data
      - PYTHONPATH=/usr/src/app
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend:/usr/src/app:delegated
      - ./data:/usr/src/app/data:ro
      - ./backend/init_vector_index.py:/usr/src/app/init_vector_index.py:ro
    command: ["python", "/usr/src/app/init_vector_index.py"]
    networks:
      - app-network

  cron_app:
    build:
      context: ./backend
      dockerfile: Dockerfile.cron
      args:
        - TARGETPLATFORM=linux/arm64
    container_name: cron_app
    depends_on:
      db_init:
        condition: service_completed_successfully
      vector_index_init:
        condition: service_completed_successfully
      qdrant:
        condition: service_healthy
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_HOST=database
      - DB_PORT=5432
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AI_ANALYZER_OPENAI_API_KEY=${AI_ANALYZER_OPENAI_API_KEY}
      - URL=${URL}
      - API_KEY=${API_KEY}
      - HOST=${HOST:-localhost}
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - PYTHONPATH=/usr/src/app/ai-analyzer
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING=UTF-8
    volumes:
      - ./backend:/usr/src/app:delegated
      - ./.env:/usr/src/app/.env:ro
      - cron_logs:/var/log
    restart: unless-stopped
    networks:
      - app-network

  qdrant:
    build:
      context: ./backend
      dockerfile: qdrant.Dockerfile
      args:
        - TARGETPLATFORM=linux/arm64
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - app-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:
    name: ai_analyzer_postgres_data
    driver: local
  cron_logs:
    name: ai_analyzer_cron_logs
    driver: local
  qdrant_data:
    name: ai_analyzer_qdrant_data
    driver: local

networks:
  app-network:
    driver: bridge