services:
  database:
    image: postgres:13
    container_name: postgres_db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST_AUTH_METHOD=md5
      - "listen_addresses=*"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    stdin_open: true
    tty: true
    networks:
      - app-network

  db_init:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: db_init
    depends_on:
      database:
        condition: service_healthy
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_HOST=database
      - DB_PORT=5432
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - READ_USER=${READ_USER}
      - READ_USER_PASSWORD=${READ_USER_PASSWORD}
    volumes:
      - ./backend:/usr/src/app:delegated
      - ./backend/init_db.py:/usr/src/app/init_db.py:ro
    command: ["python", "/usr/src/app/init_db.py"]
    networks:
      - app-network

  cron_app:
    build:
      context: ./backend
      dockerfile: Dockerfile.cron
    container_name: cron_app
    depends_on:
      db_init:
        condition: service_completed_successfully
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_HOST=database
      - DB_PORT=5432
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AI_ANALYZER_OPENAI_API_KEY=${AI_ANALYZER_OPENAI_API_KEY}
      - URL=${URL}
      - API_KEY=${API_KEY}
      - HOST=${HOST:-localhost}
      - PYTHONPATH=/usr/src/app/ai-analyzer
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING=UTF-8
    volumes:
      - ./backend:/usr/src/app:delegated
      - ./.env:/usr/src/app/.env:ro
      - cron_logs:/var/log
    restart: unless-stopped
    networks:
      - app-network

volumes:
  postgres_data:
    name: ai_analyzer_postgres_data
    driver: local
  cron_logs:
    name: ai_analyzer_cron_logs
    driver: local

networks:
  app-network:
    driver: bridge